Repository sharmaaditya570191/BossY, pull requests merged in 2020-05, with the labels that each got.

#110 Fourth component
  package.json
  src/assets/scss/fourthcontent.scss
  src/components/fourth-content.js
  src/index.js
Labels: gssoc20, medium

#109 Created Schema for Minion using Mongoose
  .gitignore
  models/minions.js
Labels: gssoc20, medium

#104 Created schema for meeting
  server/models/Meeting.js
Labels: gssoc20, medium

#86 Contact us added
  README.md
Labels: easy, gssoc20

#102 Create Idea.js
  server/models/Idea.js
Labels: gssoc20, medium

#53 updated logo
  src/assets/img/bossylogo.png
Labels: gssoc20, medium

#84 created schema of Work using mongoose
  server/models/Work.js
Labels: gssoc20, medium

#88 Connected Express to Mongodb via Mongoose
  .gitignore
  package-lock.json
  package.json
  server.js
Labels: gssoc20, hard

#106 Cookie Policy Page
  src/assets/img/toggleoff.svg
  src/assets/img/toggleon.svg
  src/assets/scss/cookiepolicy.scss
  src/components/CookiePolicy.js
  src/index.js
Labels: gssoc20, hard

#83 Created CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: gssoc20, hard

#120 Babel support added to the project.
  .babelrc
  package-lock.json
  package.json
Labels: gssoc20, hard

#121 footer component is added
  package-lock.json
  package.json
  src/assets/img/email.svg
  src/assets/img/facebook.svg
  src/assets/img/google.png
  src/assets/img/google.svg
  src/assets/img/gps.svg
  src/assets/img/icons8-google-plus-24.png
  src/assets/img/pin.svg
  src/assets/img/telephone.svg
  src/assets/img/twitter.svg
  src/assets/scss/footer.scss
  src/components/Footer.js
  src/components/Home.js
  src/index.js
Labels: gssoc20, hard

#56 changed Idea component to function component
  src/components/Idea.js
Labels: gssoc20, hard

#57 Added pull request template
  .github/pull_request_template.md
Labels: gssoc20, hard

#50 Change class to functional component work
  src/components/Work.js
Labels: gssoc20, hard

#126 Logo added
  src/assets/img/logo(Adyasha8105)/logo for bossy.xd
  src/assets/img/logo(Adyasha8105)/logo.png
Labels: gssoc20, hard, marked

#127 Logo added (2)
  src/assets/img/logo(Adyasha8105)/logo for bossy.xd
  src/assets/img/logo(Adyasha8105)/logo of bossy.xd
  src/assets/img/logo(Adyasha8105)/logo.png
  src/assets/img/logo(Adyasha8105)/logo1.png
  src/assets/img/logo(Adyasha8105)/logo2.png
Labels: design, gssoc20, hard

#108 fixes #98
  package-lock.json
  src/components/FifthPage.js
  src/components/FifthPage.scss
  src/components/ProgressBar.js
  src/index.js
Labels: gssoc20, hard

#129 Bug solved in the site
  package-lock.json
  package.json
Labels: gssoc20, hard

#130 Readme changed
  README.md
Labels: gssoc20, hard

#49 changed from react-router to @reach/router
  package-lock.json
  package.json
  src/components/AllIdeas.js
  src/components/AllMinions.js
  src/components/Heading.js
  src/components/Home.js
  src/components/Idea.js
  src/components/IdeaListItem.js
  src/components/Minion.js
  src/index.js
  src/store/minions.js
Labels: gssoc20, hard

#79 minion component converted to functional component
  src/components/Minion.js
Labels: gssoc20, hard

#128 Error page
  src/assets/css/error.css
  src/assets/img/image.jpg
  src/components/page-not-found.js
Labels: gssoc20, hard

#145 Updated README
  README.md
  package.json
Labels: gssoc20, hard

#154 Navbar is added
  src/assets/img/cross.jpg
  src/assets/img/more.png
  src/assets/img/search.png
  src/assets/scss/NavBar.scss
  src/components/App.js
  src/components/NavBar.js
Labels: gssoc20, hard

#149 Error in package.json
  package.json
Labels: easy, gssoc20

#151 Added bossy workspace in readme.md
  README.md
Labels: easy, gssoc20

#147 added necessary caches
  src/middleware/renderView.jsx
  src/shared/cache.es6
Labels: easy, gssoc20, marked

#155 added compression
  package.json
Labels: easy, gssoc20

#153 added husky as a pre git commit hook.
  package-lock.json
  package.json
Labels: easy, gssoc20, marked

#156 added the isomorphic model of cookie
  src/shared/cookies.es6
Labels: easy, gssoc20

#161 error resolved
  src/components/Footer.js
  src/components/Idea.js
  src/components/Work.js
Labels: easy, gssoc20, hard, medium
